version: "3.8"

services:
  fizzbuzz-app:
    build: .
    container_name: fizzbuzz_service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
